### ISSUE TITLE
dynamic pipeline tutorial is non-functional

### ISSUE THREAD

**Issue by wimo7083** [codefresh-io/docs.codefresh.io#133]
Duplicated issue that was closed without actually resolving:
https://github.com/codefresh-io/cli/issues/301

When I look for any information on dynamically generated pipelines these are the top three results for codefresh- of which most of it is incorrect and doesn't pass validation.
https://github.com/kostis-codefresh/dynamic-pipelines/blob/master/pipeline-creator-spec.yml
https://codefresh.io/devops-tutorial/programmatic-creation-codefresh-pipelines-part2/
https://codefresh.io/devops-tutorial/programmatic-creation-codefresh-pipelines-part1/

1. cli command is incorrect

```
@ msheiny , thanks.
There is no codefresh create pipeline command.
The ability to create a pipeline is via flag -f like codefresh create -f FILE that contains a valid yaml descriptor.
```

2. The provided files don't work and the provided validation errors fail due to the name having a slash in it.
https://github.com/codefresh-io/cli/issues/334

Documentation currently has incorrect references. It appears there is a way to get a spec only by manually creating a pipeline and then using CLI to output.

**Comment by kostis-codefresh** [comment]
Hello @wimo7083 

Thanks for reporting this. I will update the blog post ASAP to a working state.

**Comment by kostis-codefresh** [comment]
I updated the pipeline spec in https://codefresh.io/devops-tutorial/programmatic-creation-codefresh-pipelines-part1/ and it should now work with the latest Codefresh CLI version.

**Comment by kostis-codefresh** [comment]
I have now updated the git repo at https://github.com/kostis-codefresh/dynamic-pipelines and blog post as well at https://codefresh.io/devops-tutorial/programmatic-creation-codefresh-pipelines-part2/

@wimo7083 Let us know if you have other issues with dynamic pipelines

**Comment by wimo7083** [comment]
Awesome thank you.
