### ISSUE TITLE
Can a push to ECR example be added please?

### ISSUE THREAD

**Issue by NasAmin** [codefresh-io/docs.codefresh.io#146]
Before opening an issue:

- [Search for duplicate or closed issues](https://github.com/codefresh-io/docs.codefresh.io/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the [contributing guidelines](https://github.com/codefresh-io/docs.codefresh.io/blob/master/CONTRIBUTING.md)

When reporting a bug, include:

- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)

**Comment by kostis-codefresh** [comment]
Hello @NasAmin 

Codefresh is cloud agnostic. After you connect your ECR instance https://codefresh.io/docs/docs/docker-registries/external-docker-registries/amazon-ec2-container-registry/ you only need to push with the push step https://codefresh.io/docs/docs/codefresh-yaml/steps/push/#examples

There is no special instruction/configuration needed for ECR. It is exactly the same as any other registry. Or am I missing something?
