### ISSUE TITLE
demo, picture mongo-service.png - not need to create external port

### ISSUE THREAD

**Issue by curx** [codefresh-io/docs.codefresh.io#89]
Hi,

while trying out the demo of the demochat app i noticed that in the [picture](https://codefresh.io/docs/images/kubernetes/demo/mongo-service.png)  for setting up the mongodb an external port is actived, that is not needed a ClusterIP should suffice, so in the checkbox this can be deactivated.

Bye,
Thorsten

**Comment by kostis-codefresh** [comment]
Thank you. We changed the picture to show the checkbox unchecked.
